---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: forseti-linux
description: An opinionated OS tailored for software and devops engineers.

base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: 43

mounts:
  - type: cache
    id: downloads-forseti-linux-43
    destination: /var/cache/downloads
    sharing: locked
  - type: bind
    source: files/signatures
    destination: /var/signatures
    readonly: true

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: brew
    brew-analytics: false

  - type: dnf
    repos:
      files:
        - vscode.repo
    install:
      packages:
        - neovim
        - code

  - from-file: common/install-helium.yaml
  - from-file: common/install-sops.yaml

  - type: script
    scripts:
      - install-kubectl.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully